# Generated by Django 3.2 on 2021-05-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configaplicacion',
            name='upload',
        ),
        migrations.AlterField(
            model_name='configaplicacion',
            name='dirAutorizados',
            field=models.FileField(upload_to='', verbose_name='Dirección Autorizados'),
        ),
        migrations.AlterField(
            model_name='configaplicacion',
            name='passFirma',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
    ]
