# Generated by Django 3.2 on 2021-05-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleadicional',
            name='valor',
            field=models.CharField(max_length=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.CharField(default='1', max_length=50, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='importeTotal',
            field=models.CharField(max_length=50, verbose_name='Importe Total'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='propina',
            field=models.CharField(max_length=50, verbose_name='Propina'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='totalDescuento',
            field=models.CharField(max_length=10, verbose_name='Total Descuento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='totalSinImpuestos',
            field=models.CharField(max_length=10, verbose_name='Total Sin Impuestos'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='formaPago',
            field=models.CharField(choices=[('01', 'SIN UTILIZACIÓN DEL SISTEMA FINANCIERO'), ('15', 'COMPESACIÓN DE DEUDAS'), ('16', 'TARJETA DE DEBITO'), ('17', 'DINERO ELECTRONICO'), ('18', 'TARJETA PREPAGO'), ('19', 'TARJETA DE CREDITO'), ('20', 'OTROS CON UTILIZACIÓN DEL SISTEMA FINANCIERO'), ('21', 'ENDOSO DE TITULOS')], default='SIN_UTILIZACION_FINANCIERA', max_length=50, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ice',
            field=models.CharField(choices=[('3011', 'CIGARRILLOS RUBIOS'), ('3021', 'CIGARRILLOS NEGROS'), ('3023', 'PRODUCTOS DEL TABACO....')], max_length=50, null=True, verbose_name='ICE'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='irbpnr',
            field=models.CharField(choices=[('5001', 'BOTELLAS PLASTICAS NO RETORNABLES')], max_length=10, null=True, verbose_name='IRBPNR'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioUnitario',
            field=models.CharField(max_length=10, verbose_name='Precio Unitario'),
        ),
    ]
