# Generated by Django 3.2 on 2021-05-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20210504_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='campoadicional',
            name='valor',
            field=models.CharField(max_length=50, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='comprobantegeneral',
            name='dirEstablecimiento',
            field=models.CharField(max_length=100, verbose_name='Dirección Establecimiento'),
        ),
        migrations.AlterField(
            model_name='comprobantegeneral',
            name='dirMatriz',
            field=models.CharField(max_length=100, verbose_name='Dirección de la Matriz'),
        ),
        migrations.AlterField(
            model_name='comprobantegeneral',
            name='obligadoContabilidad',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=100, verbose_name='Obligado a LLevar Contabilidad'),
        ),
        migrations.AlterField(
            model_name='comprobantegeneral',
            name='tipoEmision',
            field=models.CharField(default='1', max_length=50, verbose_name='Tipo Emisión'),
        ),
        migrations.AlterField(
            model_name='configaplicacion',
            name='dirAutorizados',
            field=models.FileField(upload_to='uploads/', verbose_name='Dirección Autorizados'),
        ),
        migrations.AlterField(
            model_name='configaplicacion',
            name='dirFirma',
            field=models.FileField(upload_to='uploads/', verbose_name='Dirección Firma'),
        ),
        migrations.AlterField(
            model_name='configaplicacion',
            name='dirLogo',
            field=models.FileField(upload_to='uploads/', verbose_name='Dirección Logo'),
        ),
        migrations.AlterField(
            model_name='configcorreo',
            name='correoAsunto',
            field=models.CharField(max_length=100, verbose_name='Correo Asunto'),
        ),
        migrations.AlterField(
            model_name='configcorreo',
            name='correoHost',
            field=models.CharField(max_length=100, verbose_name='Correo Host'),
        ),
        migrations.AlterField(
            model_name='configcorreo',
            name='correoPass',
            field=models.CharField(max_length=100, verbose_name='Correo Password'),
        ),
        migrations.AlterField(
            model_name='configcorreo',
            name='correoPort',
            field=models.CharField(max_length=100, verbose_name='Correo Port'),
        ),
        migrations.AlterField(
            model_name='configcorreo',
            name='correoRemitente',
            field=models.CharField(max_length=100, verbose_name='Correo Remitente'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.CharField(max_length=50, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='descuento',
            field=models.CharField(max_length=50, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precioTotalSinImpuesto',
            field=models.CharField(max_length=50, verbose_name='Precio Total Impuesto'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='precioUnitario',
            field=models.CharField(max_length=50, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='detalleguiaremision',
            name='cantidad',
            field=models.CharField(max_length=50, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.CharField(default='DOLAR', max_length=50, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='totalSinImpuestos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totalImpuesto', to='facturacion.totalimpuesto', verbose_name='Total Sin Impuesto'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='baseImponible',
            field=models.CharField(max_length=50, verbose_name='Base Imponible'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='tarifa',
            field=models.CharField(max_length=50, verbose_name='Tarifa'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='valor',
            field=models.CharField(max_length=50, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='liquidacioncompra',
            name='moneda',
            field=models.CharField(default='DOLAR', max_length=50, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='moneda',
            field=models.CharField(default='DOLAR', max_length=50, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='totalSinImpuestos',
            field=models.CharField(max_length=50, verbose_name='Total Sin Impuesto'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='valorModificacion',
            field=models.CharField(max_length=50, verbose_name='Valor Modificación'),
        ),
        migrations.AlterField(
            model_name='totalimpuesto',
            name='baseImponible',
            field=models.CharField(choices=[('2', 'IVA'), ('3', 'ICE'), ('5', 'IRBPNR')], default='2', max_length=1, verbose_name='Base Imponible'),
        ),
        migrations.AlterField(
            model_name='totalimpuesto',
            name='codigoPorcentaje',
            field=models.CharField(choices=[('0', '0%'), ('2', '12%'), ('6', 'No objeto de impuesto'), ('7', 'Exento de IVA')], default='0', max_length=1, verbose_name='Código Porcentaje'),
        ),
        migrations.AlterField(
            model_name='totalimpuesto',
            name='descuentoAdicional',
            field=models.CharField(max_length=50, verbose_name='Descuento Adicional'),
        ),
        migrations.AlterField(
            model_name='totalimpuesto',
            name='tarifa',
            field=models.CharField(max_length=50, verbose_name='Tarifa'),
        ),
    ]
