# Generated by Django 3.2 on 2021-05-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
