# Generated by Django 3.2 on 2021-06-30 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20210520_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='detalleAdicional',
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='impuestos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion.impuesto', verbose_name='Impuesto'),
        ),
    ]
